"""initial_schema

Revision ID: 06b2d89a4b67
Revises: 
Create Date: 2026-09-06 11:33:22.292739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b2d89a4b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('sensors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('paired_animal_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_sensor_id'), 'sensors', ['sensor_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('FARMER', 'ADMIN', 'WORKER', name='userrole', native_enum=False), nullable=False),
    sa.Column('farm_name', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='animalgender', native_enum=False), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'NOT_MONITORED', name='animalhealthstatus', native_enum=False), nullable=False),
    sa.Column('sensor_status', sa.Enum('NOT_PAIRED', 'PAIRED', 'ONLINE', 'OFFLINE', name='animalsensorstatus', native_enum=False), nullable=False),
    sa.Column('paired_sensor_id', sa.String(length=50), nullable=True),
    sa.Column('paired_sensor_name', sa.String(length=100), nullable=True),
    sa.Column('sensor_paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code_payload', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_farmer_id'), 'animals', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='alertseverity', native_enum=False), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_animal_id'), 'alerts', ['animal_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_farmer_id'), 'alerts', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_table('health_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('temp_component', sa.Integer(), nullable=False),
    sa.Column('activity_component', sa.Integer(), nullable=False),
    sa.Column('rumination_component', sa.Integer(), nullable=False),
    sa.Column('alert_penalty', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_animal_id'), 'health_scores', ['animal_id'], unique=False)
    op.create_index(op.f('ix_health_scores_calculated_at'), 'health_scores', ['calculated_at'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Integer(), nullable=False),
    sa.Column('behavior', sa.String(length=50), nullable=False),
    sa.Column('rumination_mins', sa.Integer(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_animal_id'), 'sensor_readings', ['animal_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_animal_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_health_scores_calculated_at'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_animal_id'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_farmer_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_animal_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_farmer_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensors_sensor_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
